# Generated by Django 3.2.9 on 2021-11-15 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmc_rank', models.IntegerField()),
                ('date_added', models.DateTimeField()),
                ('crypto_name', models.CharField(max_length=100)),
                ('circulating_supply', models.BigIntegerField()),
                ('latest_update', models.DateTimeField()),
                ('percent_change_1hr', models.FloatField()),
                ('percent_change_24hr', models.FloatField()),
                ('percent_change_7d', models.FloatField()),
                ('percent_change_30d', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=250)),
                ('publication_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('favorite_count', models.IntegerField()),
                ('full_text', models.TextField()),
                ('tweet_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=100)),
                ('verified_user', models.BooleanField()),
                ('tweet_url', models.URLField()),
            ],
        ),
    ]
